### ISSUE TITLE
[Bug]: ZITADEL_EXTERNALSECURE: false responding with secure attribute on the cookie

### ISSUE THREAD

**Issue by cptcharisma** [zitadel/zitadel#11019]
### Preflight Checklist

- [x] I could not find a solution in the documentation, the existing issues or discussions
- [x] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

4.6.0

### Database

PostgreSQL

### Database Version

Postgres 17

### Describe the problem caused by this bug

I am trying to get the self hosted zitadel to work. My docker compose is based off the one in the docs.
```
  odyssey-zitadel:
    restart: unless-stopped
    image: ghcr.io/zitadel/zitadel:v4.6.0
    command: start-from-init --masterkey "MasterkeyNeedsToHave32Characters"
    environment:
      # See "What's next" to learn about how to serve Zitadel on a different domain or IP.
      ZITADEL_EXTERNALDOMAIN: odyssey-zitadel.lan

      # See "What's next" to learn about how to enable TLS.
      ZITADEL_EXTERNALSECURE: false
      ZITADEL_TLS_ENABLED: false
      
      # Database connection settings.
      ZITADEL_DATABASE_POSTGRES_HOST: db
      ZITADEL_DATABASE_POSTGRES_PORT: 5432
      # The database is created by the init job if it does not exist.
      ZITADEL_DATABASE_POSTGRES_DATABASE: zitadel
      # The admin user must already exist in the database.
      ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME: postgres
      ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD: postgres
      ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE: disable
      # The zitadel user is created by the init job if it does not exist.
      ZITADEL_DATABASE_POSTGRES_USER_USERNAME: zitadel
      ZITADEL_DATABASE_POSTGRES_USER_PASSWORD: zitadel
      ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE: disable
      
      # By configuring a login client, the setup job creates a user of type machine with the role IAM_LOGIN_CLIENT.
      # It writes a PAT to the path specified in ZITADEL_FIRSTINSTANCE_LOGINCLIENTPATPATH.
      # The PAT is passed to the login container via the environment variable ZITADEL_SERVICE_USER_TOKEN_FILE.
      ZITADEL_FIRSTINSTANCE_LOGINCLIENTPATPATH: /current-dir/login-client.pat
      ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORDCHANGEREQUIRED: false
      ZITADEL_FIRSTINSTANCE_ORG_LOGINCLIENT_MACHINE_USERNAME: login-client
      ZITADEL_FIRSTINSTANCE_ORG_LOGINCLIENT_MACHINE_NAME: Automatically Initialized IAM_LOGIN_CLIENT
      ZITADEL_FIRSTINSTANCE_ORG_LOGINCLIENT_PAT_EXPIRATIONDATE: '2029-01-01T00:00:00Z'
      # Activate the login v2 on an installation from scratch.
      # To activate the login v2 on an existing installation, read the "What's next" section.
      ZITADEL_DEFAULTINSTANCE_FEATURES_LOGINV2_REQUIRED: true # To use the login v1, set this to false.
      ZITADEL_DEFAULTINSTANCE_FEATURES_LOGINV2_BASEURI: http://odyssey-zitadel.lan:3003/ui/v2/login
      # Configure the redirection paths to the login v2.
      ZITADEL_OIDC_DEFAULTLOGINURLV2: http://odyssey-zitadel.lan:3003/ui/v2/login/login?authRequest=
      ZITADEL_OIDC_DEFAULTLOGOUTURLV2: http://odyssey-zitadel.lan:3003/ui/v2/login/logout?post_logout_redirect=
      ZITADEL_SAML_DEFAULTLOGINURLV2: http://odyssey-zitadel.lan:3003/ui/v2/login/login?samlRequest=

      # By configuring a machine, the setup job creates a user of type machine with the role IAM_OWNER.
      # It writes a personal access token (PAT) to the path specified in ZITADEL_FIRSTINSTANCE_PATPATH.
      # The PAT can be used to provision resources with [Terraform](/docs/guides/manage/terraform-provider), for example.
      # ZITADEL_FIRSTINSTANCE_PATPATH: /current-dir/admin.pat
      # ZITADEL_FIRSTINSTANCE_ORG_MACHINE_MACHINE_USERNAME: admin
      # ZITADEL_FIRSTINSTANCE_ORG_MACHINE_MACHINE_NAME: Automatically Initialized IAM_OWNER
      # ZITADEL_FIRSTINSTANCE_ORG_MACHINE_PAT_EXPIRATIONDATE: '2029-01-01T00:00:00Z'
      
      # To change the initial human admin users username and password, uncomment the following lines.
      # The first login name is formatted like this: <username>@<org_name>.<external_domain>
      # With the following incommented configuration, this would be root@my-organization.localhost
      # Visit http://localhost:8080/ui/console to check if the login name works.
      # If you can't log in, check the available login names:
      # echo "select * from projections.login_names3;" | psql -h localhost -U postgres -d zitadel
      # The postgres users password is postgres.
      ZITADEL_FIRSTINSTANCE_ORG_NAME: Pegasus Organization
      ZITADEL_FIRSTINSTANCE_ORG_HUMAN_USERNAME: admin
      ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORD: 'aA123456789!'

      # Enable debug logs
      ZITADEL_LOG_LEVEL: debug     
      # Write Access Logs to stdout.
      # ZITADEL_LOGSTORE_ACCESS_STDOUT_ENABLED: true

    # healthcheck:
    #   test:
    #     - CMD
    #     - /app/zitadel
    #     - ready
    #   interval: 10s
    #   timeout: 60s
    #   retries: 5
    #   start_period: 10s
    user: "0"
    volumes:
      - /plunk/apps/zitadel/zitadel:/current-dir:delegated
    ports:
      - 8088:8080
      - 3003:3000
    networks:
      - elk-net
    depends_on:
      db:
        condition: service_healthy

  odyssey-login:
    restart: unless-stopped
    image: ghcr.io/zitadel/zitadel-login:v4.6.0
    # If you can't use the network_mode service:zitadel, you can pass the environment variables ZITADEL_API_URL=http://zitadel:8080 and CUSTOM_REQUEST_HEADERS=Host:localhost instead.
    environment:
      - ZITADEL_API_URL=http://localhost:8080
      - CUSTOM_REQUEST_HEADERS=Host:odyssey-zitadel.lan
      - NEXT_PUBLIC_BASE_PATH=/ui/v2/login
      - ZITADEL_SERVICE_USER_TOKEN_FILE=/current-dir/login-client.pat
    network_mode: service:odyssey-zitadel
    user: "0"
    volumes:
      - /plunk/apps/zitadel/zitadel:/current-dir:ro
    # depends_on:
    #   odyssey-zitadel:
    #     condition: service_healthy
    #     restart: false
```

Not worrying about redaction above as it is a separate network. I have had the UI work before, but due to me debugging this issue, the containers have been recreated a few times.  

I run nginx locally and use http for my homelab. My suspicion is on the secure attribute returned on the cookie here.
<img width="3344" height="1238" alt="Image" src="https://github.com/user-attachments/assets/a2c14f55-fcd9-4094-a09d-b3edf31a0485" />

Can you help me understand why the secure attribute is set even when the setting is disabled?
Also putting in the wrong password, the UI says "Could not create session for user".
Putting in the right password, as the screenshot says: "Could not verify password".

### To reproduce

Steps to reproduce:
1. Use docker compose to create these containers. I used portainer UI
2. Go to the login UI
3. Try to login as admin
4. Look at network tab on chrome dev tools to spot the cookie setting

### Screenshots

Already added above

### Operating System

Ubuntu 25.04

### Additional Context

I understand that to productionalize, I will need TLS.

**Comment by wanderingMonk88** [comment]
To unblock myself, I made nginx host a self signed cert for this and set --tlsMode=external. This terminates ssl at nginx. And I can successfully login now. So the issue must most definitely be with the secure attribute on the cookie.

**Comment by ostempel** [comment]
I ran into the same issue. Your solution works in order to make the login work again. Our problem is that our oidc discovery package doesn't support skipping TLS verification at the moment and fails because it doesn't trust the CA because of the self-signed cert.

Maybe this is a hint why it doesn't work:
https://github.com/zitadel/zitadel/blob/14038716e3261f331a1baa687cb9a04865cfaeaf/apps/login/src/lib/cookies.ts#L43

And in the Dockerimage gets build like this:
(https://github.com/zitadel/zitadel/blob/14038716e3261f331a1baa687cb9a04865cfaeaf/apps/login/Dockerfile#L13)

If I set the `NODE_ENV` to "test" or "development" in the container spec, it doesn't change anything. So I suspect that it get resolved at buildtime and can't be changed at runtime. I may be wrong and just had little time to inspect this. Also I don't really understand the build-process

**Comment by nibraz-rehaman** [comment]
> To unblock myself, I made nginx host a self signed cert for this and set --tlsMode=external. This terminates ssl at nginx. And I can successfully login now. So the issue must most definitely be with the secure attribute on the cookie.

I tried this, it still isn't working

can u help me with this?

**Comment by wanderingMonk88** [comment]
Here are the steps I used:
**Self Signed Certificate Setup**
1.  Issue the following command to generate a self signed cert.
```
openssl req -x509 -nodes -newkey rsa:4096 \
  -keyout zitadel.key \
  -out zitadel.crt \
  -days 365 \
  -subj "/CN=odyssey-zitadel.lan"
```

That generates zitadel.key and zitadel.crt.
2. I use nginx proxy manager, go to the certificates tab. Click add certificate -> 'Custom Certificate'. Upload the files created above and give it a name.
3. Go to proxy hosts and edit your entry for zitadel. Go to the ssl tab and set it as the self signed certificate created above.

**Zitadel Docker Setup**
1. Update your docker compose to add the tlsMode like ```command: start-from-init --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode=external```


Now navigate to https://<your-zitadel-dns>. Try logging in and ensure the dev console does not show the secure warning like the original screenshot.

**Comment by fforootd** [comment]
Hm, I need to check, but this could well be a bug.

Out of curiosity though. Why do you want to run Zitadel without TLS, its not exactly something we encourage 😁

**Comment by ostempel** [comment]
> Hm, I need to check, but this could well be a bug.
> 
> Out of curiosity though. Why do you want to run Zitadel without TLS, its not exactly something we encourage 😁

We want to provide a OIDC-Provider in our [local lab env](https://github.com/metal-stack/mini-lab) to simplify login and five some nice user-experience. But in the lab to provide TLS in a local setup is quite a hustle. In production we will use TLS of course.
